run gke

diff --git a/.github/workflows/google.yaml b/.github/workflows/google.yaml
--- a/.github/workflows/google.yaml
+++ b/.github/workflows/google.yaml
@@ -28,28 +28,28 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
+      # - name: Terraform Format
+      #   id: fmt
+      #   run: terraform fmt -check
 
-      - name: Terraform Init
-        id: init
-        run: terraform init
+      # - name: Terraform Init
+      #   id: init
+      #   run: terraform init
 
-      - name: Terraform Plan
-        id: plan
-        # if: github.event_name == 'pull_request'
-        run: terraform plan -no-color
-        continue-on-error: true
+      # - name: Terraform Plan
+      #   id: plan
+      #   # if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color
+      #   continue-on-error: true
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1      
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1      
 
-      - name: Terraform Apply
-        # if: github.ref == 'refs/heads/master' && github.event_name == 'push' 
-        run: |
-          terraform apply -auto-approve
+      # - name: Terraform Apply
+      #   # if: github.ref == 'refs/heads/master' && github.event_name == 'push' 
+      #   run: |
+      #     terraform apply -auto-approve
   
   bootstrap:
     name: bootstrap-cluster
@@ -57,7 +57,6 @@ jobs:
     needs: terraform
     steps:    
       - id: get-credentials
-        if: github.ref == 'refs/heads/master' && github.event_name == 'push' 
         uses: google-github-actions/get-gke-credentials@main
         with:
           cluster_name: servian
